vich_uploader:
    db_driver: orm

    mappings:
        whatsapp_media:
                    uri_prefix:         '%app.path.medias%'
                    upload_destination: '%kernel.project_dir%/public%app.path.medias%'
